### ISSUE TITLE
Front End Validation for Email Regex Validation 

### ISSUE THREAD

**Issue by gutsy** [adobe/dynamic-workflow#25]
Followup on #14 

Submitting form currently will show an error message and prevent it from sending data to Sign, but there is no indicator before the form is submitted.

**Comment by umuur** [comment]
Hi there, can I claim this issue?

**Comment by gutsy** [comment]
Heck yeah you can.

**Comment by umuur** [comment]
@gutsy I couldn't move forward due to #27. Do you have any idea about it?

**Comment by gutsy** [comment]
@umuur I ended up just running it locally, I haven't touched Digital Ocean yet. Did you make sure that the required options were set up in the config file? Are there any errors coming back from when it tries to get the workflows?

**Comment by umuur** [comment]
@gutsy I've just tried locally, I'm getting the error below:

```
(node:882) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://127.0.0.1/api/rest/v5/workflows reason: Unexpected token < in JSON at position 0
    at /mnt/c/Users/umurd/dynamic-workflow/node_modules/node-fetch/lib/index.js:272:32
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:882) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:882) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by gutsy** [comment]
is this set on the config file?

x-api-user: ""

Can just be an empty string.

**Comment by umuur** [comment]
It was: `x-api-user: ""`

when I add my e-mail, the error gone but the dropdown still looks empty.

x-api-user: "email:mymail@domain.com"

**Comment by umuur** [comment]
it was `x-api-user: "" `

I tried `x-api-user:"email:mymail@domain.com"` but I got the same error.

**Comment by gutsy** [comment]
And you have the integration property set under enterprise?

**Comment by umuur** [comment]
Yes, It is set to my Adobe Sign integration key which has all privileges.

**Comment by gutsy** [comment]
I am not sure, then. @nwcell @gkolluri could either of you help troubleshoot this with him? I haven't seen this error yet.

**Comment by umuur** [comment]
Adobe Sign Integration Key which I'm using is belongs to trial account. Does this can be the issue?

**Comment by nwcell** [comment]
@umuur, can you share the payload that you are getting in response w/ that error?
